# SPDX-License-Identifier: Apache-2.0
"""Catálogo do inglês: o texto em português, que é a chave, e o texto em inglês.

Toda chave é um texto que o painel passa por t(), tn() ou N() (idioma.py), escrito igual ao do código. A tradução
mantém os nomes entre chaves, as marcas do HTML e as aspas da chave; os valores entram depois, já prontos para o
HTML. O scripts/validate.sh confere se cada texto do código tem tradução aqui e se não sobra nenhuma.
"""
import re

EN = {
    'A sua conta de administrador não existe mais. Saia e entre de novo.':
        'Your administrator account no longer exists. Sign out and sign in again.',
    'Administrador não encontrado':
        'Administrator not found',
    'Ninguém remove a própria conta, para o painel nunca ficar sem administrador. Peça a outro '
    'administrador para removê-la.':
        'Nobody removes their own account, so the panel is never left without an administrator. Ask '
        'another administrator to remove it.',
    'A sua senha antiga deixa de valer na hora e as outras sessões desse administrador são encerradas.':
        'Your old password stops working immediately and the other sessions of this administrator are '
        'closed.',
    'A senha de <strong>{nome}</strong> antiga deixa de valer na hora e as outras sessões desse '
    'administrador são encerradas.':
        'The old password of <strong>{nome}</strong> stops working immediately and the other sessions '
        'of this administrator are closed.',
    'Já existe um administrador com este nome.':
        'There is already an administrator with this name.',
    'Limite de {maximo} administradores atingido: remova um antes de criar outro.':
        'Limit of {maximo} administrators reached: remove one before creating another.',
    'Administrador criado':
        'Administrator created',
    'Trocar senha':
        'Change password',
    'Este administrador não existe mais.':
        'This administrator no longer exists.',
    'Senha trocada':
        'Password changed',
    'Trocar nome':
        'Change name',
    'Remover administrador':
        'Remove administrator',
    'Nome inválido. Veja a regra abaixo do campo.':
        'Invalid name. See the rule below the field.',
    'O nome novo é igual ao atual.':
        'The new name is the same as the current one.',
    'Voltar para a lista':
        'Back to the list',
    'Administrador <strong>{nome}</strong>. Senha gerada pelo painel:':
        'Administrator <strong>{nome}</strong>. Password generated by the panel:',
    'Copie agora para o seu cofre de senhas ou entregue a quem vai usar. Ela <strong>não será mostrada '
    'de novo</strong>: o painel guarda só o hash.':
        'Copy it now to your password vault or hand it to whoever will use it. It <strong>will not be '
        'shown again</strong>: the panel keeps only the hash.',
    'Já copiei: voltar para a lista':
        'Copied: back to the list',
    'Trocar senha de administrador':
        'Change administrator password',
    'Cancelar':
        'Cancel',
    'Trocar nome de administrador':
        'Change administrator name',
    'Administrador <strong>{nome}</strong>. A senha continua a mesma; o nome antigo deixa de entrar na '
    'hora.':
        'Administrator <strong>{nome}</strong>. The password stays the same; the old name stops '
        'signing in immediately.',
    'Nome novo':
        'New name',
    'Letras minúsculas, números, <code>_</code> e <code>-</code>; começa com letra ou <code>_</code>; '
    'até 32 caracteres.':
        'Lowercase letters, digits, <code>_</code> and <code>-</code>; starts with a letter or '
        '<code>_</code>; up to 32 characters.',
    'Esta é a sua conta':
        'This is your account',
    'Remover <strong>{nome}</strong>? Ele deixa de entrar no painel na hora e as sessões abertas dele '
    'são encerradas. Os usuários do FTP e os arquivos não mudam.':
        'Remove <strong>{nome}</strong>? They stop signing in to the panel immediately and their open '
        'sessions are closed. FTP users and files do not change.',
    'Sim, remover o administrador':
        'Yes, remove the administrator',
    'Não foi possível gravar o arquivo de administradores:':
        'Could not write the administrators file:',
    'erro de disco':
        'disk error',
    'Letras, números, <code>_</code>, <code>-</code> e ponto; não começa com ponto; até 64 caracteres.':
        'Letters, digits, <code>_</code>, <code>-</code> and dot; does not start with a dot; up to 64 '
        'characters.',
    'Caminho não aceito.':
        'Path not accepted.',
    'Link simbólico não é seguido pelo painel.':
        'The panel does not follow symbolic links.',
    'Pasta ou arquivo não encontrado.':
        'Folder or file not found.',
    'Pasta criada.':
        'Folder created.',
    'Nome trocado.':
        'Name changed.',
    'Apagado.':
        'Deleted.',
    'A pasta tem mais do que o painel apaga de uma vez ({maximo} itens ou {prazo} segundos por '
    'pedido). Repita para continuar.':
        'The folder holds more than the panel deletes at once ({maximo} items or {prazo} seconds per '
        'request). Repeat to continue.',
    'Um item não pôde ser apagado, ou a pasta recebeu arquivo durante a limpeza. Confira a pasta e '
    'repita.':
        'An item could not be deleted, or the folder received a file during the cleanup. Check the '
        'folder and repeat.',
    'O painel já está apagando outra pasta. Espere terminar e repita.':
        'The panel is already deleting another folder. Wait for it to finish and repeat.',
    'Trocar o nome da pasta <strong>{nome}</strong>, em {onde}.':
        'Rename the folder <strong>{nome}</strong>, in {onde}.',
    'Trocar o nome do arquivo <strong>{nome}</strong>, em {onde}.':
        'Rename the file <strong>{nome}</strong>, in {onde}.',
    'Trocar o nome do link simbólico <strong>{nome}</strong>, em {onde}.':
        'Rename the symbolic link <strong>{nome}</strong>, in {onde}.',
    'Trocar o nome do arquivo especial <strong>{nome}</strong>, em {onde}.':
        'Rename the special file <strong>{nome}</strong>, in {onde}.',
    'Apagar a pasta <strong>{nome}</strong> e <strong>tudo o que há dentro dela</strong>: {arquivos} '
    'arquivo(s), {tamanho}, em {onde}?':
        'Delete the folder <strong>{nome}</strong> and <strong>everything inside it</strong>: '
        '{arquivos} file(s), {tamanho}, in {onde}?',
    'Apagar o arquivo <strong>{nome}</strong>, de {tamanho}, modificado em {quando}, em {onde}?':
        'Delete the file <strong>{nome}</strong>, {tamanho}, modified on {quando}, in {onde}?',
    'Apagar o link simbólico <strong>{nome}</strong>; o destino dele não é tocado, em {onde}?':
        'Delete the symbolic link <strong>{nome}</strong>; its target is not touched, in {onde}?',
    'Apagar o arquivo especial <strong>{nome}</strong>; o destino dele não é tocado, em {onde}?':
        'Delete the special file <strong>{nome}</strong>; its target is not touched, in {onde}?',
    'A pasta <strong>{nome}</strong> não é renomeada por aqui: é a pasta, ou tem dentro dela a pasta, '
    'de {de_quem}.':
        'The folder <strong>{nome}</strong> cannot be renamed here: it is, or contains, the folder of '
        '{de_quem}.',
    'A pasta <strong>{nome}</strong> não é apagada por aqui: é a pasta, ou tem dentro dela a pasta, de '
    '{de_quem}.':
        'The folder <strong>{nome}</strong> cannot be deleted here: it is, or contains, the folder of '
        '{de_quem}.',
    'Tamanho':
        'Size',
    'Modificado':
        'Modified',
    'A pasta nasce vazia, dentro da sua pasta no FTP.':
        'The folder starts empty, inside your FTP folder.',
    'A pasta nasce vazia; para um equipamento gravar nela, crie um usuário com esta pasta.':
        'The folder starts empty; for a device to write to it, create a user with this folder.',
    'outro usuário do FTP':
        'another FTP user',
    'Peça ao administrador do painel.':
        'Ask the panel administrator.',
    'Para dar outra pasta a um usuário, use <strong>Usuários ➜ Editar</strong>. Para apagar a pasta '
    'junto com o usuário, use <strong>Usuários ➜ Remover</strong>.':
        'To give a user another folder, use <strong>Users ➜ Edit</strong>. To delete the folder '
        'together with the user, use <strong>Users ➜ Remove</strong>.',
    'Apagado em parte':
        'Partly deleted',
    'Nada foi apagado':
        'Nothing was deleted',
    'Início':
        'Home',
    'Renomear':
        'Rename',
    'Apagar':
        'Delete',
    'Pasta vazia':
        'Empty folder',
    'O que for enviado para ela por FTP aparece aqui.':
        'Whatever is sent to it by FTP shows up here.',
    'O painel navega, baixa, cria pasta, troca o nome e apaga; enviar arquivo continua sendo feito por '
    'FTP. Apagar pede a sua senha atual e não tem lixeira. Todo download e toda alteração ficam '
    'registrados na aba Atividade.':
        'The panel browses, downloads, creates folders, renames and deletes; uploading files is still '
        'done by FTP. Deleting asks for your current password and there is no recycle bin. Every '
        'download and every change is recorded on the Activity tab.',
    'Arquivos':
        'Files',
    'Nova pasta':
        'New folder',
    'Nome da pasta, criada dentro de <code>{onde}</code>':
        'Name of the folder, created inside <code>{onde}</code>',
    'Criar pasta':
        'Create folder',
    'O limite deste usuário é de {quantos} arquivo(s) por vez.':
        'This user is limited to {quantos} file(s) at a time.',
    'Meus arquivos':
        'My files',
    'link simbólico':
        'symbolic link',
    'arquivo especial':
        'special file',
    'Esta pasta tem mais de {maximo} itens: a lista mostra só os primeiros {maximo}. Para ver todos, '
    'entre por FTP.':
        'This folder has more than {maximo} items: the list shows only the first {maximo}. To see all '
        'of them, connect by FTP.',
    'Pasta do usuário do FTP: <strong>{donos}</strong>.':
        'Folder of the FTP user: <strong>{donos}</strong>.',
    'Novo usuário nesta pasta':
        'New user in this folder',
    'Nome não aceito':
        'Name not accepted',
    'Use letras, números, _, - e ponto; o nome não começa com ponto e tem até 64 caracteres.':
        'Use letters, digits, _, - and dot; the name does not start with a dot and has up to 64 '
        'characters.',
    'Nome já usado':
        'Name already in use',
    'Já existe uma pasta ou um arquivo com este nome.':
        'There is already a folder or a file with this name.',
    'Pasta não criada':
        'Folder not created',
    'Não foi possível criar a pasta.':
        'Could not create the folder.',
    'ou mais':
        'or more',
    '<strong>{itens}</strong> item(ns) apagado(s); o restante continua no lugar.':
        '<strong>{itens}</strong> item(s) deleted; the rest is still in place.',
    'O painel entrega até {maximo} arquivos por vez.':
        'The panel delivers up to {maximo} files at a time.',
    'Pedido recusado':
        'Request refused',
    'Voltar para {tela}':
        'Back to {tela}',
    'pasta':
        'folder',
    'Abrir':
        'Open',
    'Nome':
        'Name',
    'Ações':
        'Actions',
    'Voltar para a pasta':
        'Back to the folder',
    'Pasta de usuário do FTP':
        'Folder of an FTP user',
    'O que está dentro dela pode ser renomeado e apagado item por item.':
        'What is inside it can be renamed and deleted item by item.',
    'O item continua na mesma pasta: o painel não move de uma pasta para outra. O equipamento que '
    'grava com o nome antigo cria outro arquivo no envio seguinte.':
        'The item stays in the same folder: the panel does not move items between folders. A device '
        'that writes with the old name creates another file on its next upload.',
    'Nome não aceito. Veja a regra abaixo do campo.':
        'Name not accepted. See the rule below the field.',
    'O item já tem este nome.':
        'The item already has this name.',
    'O painel <strong>não tem lixeira</strong>: o que for apagado só volta de uma cópia de segurança.':
        'The panel <strong>has no recycle bin</strong>: what is deleted only comes back from a backup.',
    'Conferi o nome e quero apagar':
        'I checked the name and want to delete',
    'Apagar de vez':
        'Delete for good',
    'Marque a caixa de confirmação. Nada foi apagado.':
        'Tick the confirmation box. Nothing was deleted.',
    'Repetir':
        'Repeat',
    'Voltar':
        'Back',
    'Baixar':
        'Download',
    'não abre aqui':
        'does not open here',
    'O que os equipamentos já enviaram, pasta por pasta.':
        'What the devices have already sent, folder by folder.',
    'O que dá para fazer nesta aba':
        'What can be done on this tab',
    'Não foi possível trocar o nome.':
        'Could not change the name.',
    'Muitos downloads ao mesmo tempo':
        'Too many downloads at the same time',
    'Espere um deles terminar e repita.':
        'Wait for one of them to finish and repeat.',
    'para apagar':
        'to delete',
    'administrador':
        'administrator',
    'usuário':
        'user',
    'versão':
        'version',
    'ação':
        'action',
    'conferência':
        'check',
    'senha':
        'password',
    'conta':
        'account',
    'conta nova':
        'new account',
    'pasta anterior':
        'previous folder',
    'endereço pedido':
        'requested address',
    'tamanho':
        'size',
    'endereço':
        'address',
    'Quem entrou e o que foi feito no painel: os últimos 300 registros, do mais novo para o mais '
    'antigo.':
        'Who signed in and what was done on the panel: the last 300 records, newest first.',
    'Painel iniciado':
        'Panel started',
    'Entrada':
        'Sign-in',
    'Entrada recusada':
        'Sign-in refused',
    'Entrada bloqueada pelo limite de tentativas':
        'Sign-in blocked by the attempt limit',
    'Saída':
        'Sign-out',
    'Sessão de usuário do FTP encerrada':
        'FTP user session closed',
    'Usuário criado':
        'User created',
    'Pasta do usuário trocada':
        'User folder changed',
    'Perfil do usuário trocado':
        'User profile changed',
    'Limites do usuário alterados':
        'User limits changed',
    'Bloqueio do usuário no FTP removido':
        'FTP block of the user removed',
    'Endereço bloqueado por erros de usuário e senha':
        'Address blocked for user name and password errors',
    'Prazo do bloqueio de endereço alterado':
        'Address block period changed',
    'Endereço desbloqueado':
        'Address unblocked',
    'Usuário removido':
        'User removed',
    'Usuário dispensado do TLS':
        'User exempted from TLS',
    'Usuário volta a exigir TLS':
        'User requires TLS again',
    'Alteração não concluída':
        'Change not completed',
    'Arquivo baixado':
        'File downloaded',
    'Pasta criada':
        'Folder created',
    'Arquivo ou pasta renomeado':
        'File or folder renamed',
    'Arquivo ou pasta apagado':
        'File or folder deleted',
    'Download interrompido':
        'Download interrupted',
    'Administrador inicial criado':
        'Initial administrator created',
    'Senha de administrador trocada':
        'Administrator password changed',
    'Administrador renomeado':
        'Administrator renamed',
    'Administrador removido':
        'Administrator removed',
    'Administrador definido pelo host':
        'Administrator set from the host',
    'Senha atual recusada':
        'Current password refused',
    'Senha do FTP recusada na confirmação':
        'FTP password refused on confirmation',
    'Envio sem token válido':
        'Submission without a valid token',
    'Envio de outra origem':
        'Submission from another origin',
    'Endereço não aceito':
        'Address not accepted',
    'Cliente fora das redes permitidas':
        'Client outside the allowed networks',
    'Pedido de endereço bloqueado':
        'Request from a blocked address',
    'Caminho de arquivo recusado':
        'File path refused',
    'Tela fora do papel ou do perfil pedida por usuário do FTP':
        'Screen outside the role or profile requested by an FTP user',
    'Nada registrado ainda':
        'Nothing recorded yet',
    'Cada entrada no painel e cada alteração feita por ele passa a aparecer aqui.':
        'Every sign-in to the panel and every change made through it will show up here.',
    'Atividade':
        'Activity',
    'no servidor':
        'on the server',
    'Nada registrado ainda.':
        'Nothing recorded yet.',
    'De onde':
        'From',
    'Quando':
        'When',
    'O que aconteceu':
        'What happened',
    'Detalhe':
        'Detail',
    'O que fica registrado':
        'What is recorded',
    'Senha e token nunca são gravados. As transferências dos equipamentos ficam no log do serviço FTP.':
        'Passwords and tokens are never written. Transfers made by the devices are in the FTP service '
        'log.',
    '{erros} erros no FTP':
        '{erros} errors on FTP',
    '{erros} erros no painel':
        '{erros} errors on the panel',
    'Endereço liberado: ele volta a entrar no FTP e no painel.':
        'Address released: it can connect to FTP and to the panel again.',
    'Prazo do bloqueio alterado.':
        'Block period changed.',
    'Este endereço não está mais bloqueado.':
        'This address is no longer blocked.',
    'O endereço que passa de {erros} de usuário e senha em {horas}, no FTP ou no painel, fica {dias} '
    'sem entrar nos dois.':
        'An address with more than {erros} in user name and password within {horas}, on FTP or on the '
        'panel, is kept out of both for {dias}.',
    'menos de 1 dia':
        'less than 1 day',
    '{dias} dias':
        '{dias} days',
    'O bloqueio automático está desligado (<code>BLOQUEIO_ENDERECO_ERROS=0</code>): aqui ficam só os '
    'endereços bloqueados pelo terminal.':
        'Automatic blocking is off (<code>BLOQUEIO_ENDERECO_ERROS=0</code>): only addresses blocked '
        'from the terminal are listed here.',
    'nenhum endereço bloqueado':
        'no address blocked',
    '1 endereço bloqueado':
        '1 address blocked',
    '{n} endereços bloqueados':
        '{n} addresses blocked',
    'Bloqueado por <strong>{quem}</strong>, com {erros} erros de usuário e senha, em {desde}.':
        'Blocked by <strong>{quem}</strong>, with {erros} user name and password errors, on {desde}.',
    'Bloqueado por <strong>{quem}</strong>, em {desde}.':
        'Blocked by <strong>{quem}</strong>, on {desde}.',
    '{n} erro':
        '{n} error',
    '{n} erros':
        '{n} errors',
    '{n} hora':
        '{n} hour',
    '{n} horas':
        '{n} hours',
    '{n} dia':
        '{n} day',
    '{n} dias':
        '{n} days',
    'Usuários bloqueados no FTP':
        'Users blocked on FTP',
    'Bloqueio curto, de um usuário para um endereço: os outros usuários seguem entrando por ele. Vence '
    'sozinho e é desfeito em Editar, na aba Usuários.':
        'Short block, of one user for one address: other users still connect through it. It expires on '
        'its own and is undone under Edit, on the Users tab.',
    'Usuário':
        'User',
    'Origem':
        'Origin',
    'Senhas erradas':
        'Wrong passwords',
    'Bloqueado em':
        'Blocked on',
    'Até':
        'Until',
    'Nenhum endereço bloqueado com esse trecho':
        'No blocked address with that text',
    'Confira os números ou veja a lista inteira.':
        'Check the numbers or see the whole list.',
    'Bloqueios':
        'Blocks',
    'Bloqueio de {ip}':
        'Block of {ip}',
    'Nenhum endereço bloqueado agora':
        'No address blocked right now',
    'Quem passar do limite de erros de usuário e senha, no FTP ou no painel, aparece aqui.':
        'Whoever goes over the limit of user name and password errors, on FTP or on the panel, shows '
        'up here.',
    'Nada é bloqueado sozinho nesta instalação: só pelo terminal do servidor.':
        'Nothing is blocked automatically on this installation: only from the server terminal.',
    'Procurar endereço':
        'Search address',
    'Procurar':
        'Search',
    'Mostrando os {mostrados} mais recentes de {achados}: use a busca para chegar aos outros.':
        'Showing the {mostrados} most recent of {achados}: use the search to reach the others.',
    'Prazo inválido: de 1 a 3650 dias.':
        'Invalid period: 1 to 3650 days.',
    'Bloqueado por':
        'Blocked by',
    'Desde':
        'Since',
    'Mudar prazo':
        'Change period',
    'Desbloquear':
        'Unblock',
    'Endereço':
        'Address',
    'Bloqueio de <code>{ip}</code>':
        'Block of <code>{ip}</code>',
    'Prazo':
        'Period',
    'Vale até <strong>{ate}</strong> ({falta}).':
        'Valid until <strong>{ate}</strong> ({falta}).',
    'Manter bloqueado por <span class="suave">(dias, contados de agora; de 1 a 3650)</span>':
        'Keep blocked for <span class="suave">(days, counted from now; 1 to 3650)</span>',
    'O prazo novo substitui o atual: serve para bloquear por mais tempo ou para encurtar o bloqueio.':
        'The new period replaces the current one: it serves to block for longer or to shorten the '
        'block.',
    'Gravar prazo':
        'Save period',
    'O endereço volta a entrar no FTP e no painel no próximo pedido, e a contagem dos erros dele '
    'recomeça.':
        'The address can connect to FTP and to the panel again on the next request, and its error '
        'count starts over.',
    'Antes de desbloquear, corrija a senha no equipamento: se ele continuar errando, o bloqueio volta.':
        'Before unblocking, fix the password on the device: if it keeps failing, the block comes back.',
    'Abrir o usuário':
        'Open the user',
    '{regra} Agora: {total}.':
        '{regra} Now: {total}.',
    'Como funciona o bloqueio por endereço':
        'How blocking by address works',
    'Não foi possível gravar:':
        'Could not save:',
    'Não foi possível desbloquear:':
        'Could not unblock:',
    'Ver todos':
        'See all',
    'Nunca são bloqueados sozinhos o próprio servidor, a rede interna da stack e os proxies de '
    '<code>PAINEL_PROXY_CONFIAVEL</code>. Administrador que ficou com o próprio endereço bloqueado '
    'libera pelo servidor: <code>./manage-user.sh endereco-liberar &lt;endereço&gt;</code>.':
        'The server itself, the internal network of the stack and the proxies in '
        '<code>PAINEL_PROXY_CONFIAVEL</code> are never blocked automatically. An administrator whose '
        'own address got blocked releases it from the server: <code>./manage-user.sh endereco-liberar '
        '&lt;address&gt;</code>.',
    'O endereço bloqueado é recusado com qualquer conta, mesmo com a senha certa, no FTP (com e sem '
    'TLS, em modo ativo ou passivo) e no painel. Desbloquear vale no próximo pedido; mudar o prazo '
    'serve para bloquear por mais tempo ou para encurtar.':
        'A blocked address is refused with any account, even with the right password, on FTP (with and '
        'without TLS, in active or passive mode) and on the panel. Unblocking takes effect on the next '
        'request; changing the period serves to block for longer or to shorten it.',
    'Arquivos da pasta do usuário <strong>{usuario}</strong> no FTP.':
        'Files in the folder of the user <strong>{usuario}</strong> on FTP.',
    'Os arquivos da sua pasta no FTP, para navegar e baixar.':
        'The files in your FTP folder, to browse and download.',
    'Aqui você navega e baixa. O perfil desta conta é de leitura: ela não cria, não envia, não '
    'renomeia e não apaga nada, nem aqui nem por FTP. Todo download fica registrado.':
        'Here you browse and download. This account has the read-only profile: it does not create, '
        'upload, rename or delete anything, here or by FTP. Every download is recorded.',
    'Os arquivos da sua pasta no FTP, para navegar, baixar e criar pasta.':
        'The files in your FTP folder, to browse, download and create folders.',
    'Aqui você navega, baixa e cria pasta; enviar arquivo continua sendo feito por FTP. O perfil desta '
    'conta é de envio: o que já foi enviado não é renomeado nem apagado por ela. Todo download e toda '
    'pasta criada ficam registrados.':
        'Here you browse, download and create folders; uploading files is still done by FTP. This '
        'account has the upload profile: what was already sent is not renamed or deleted by it. Every '
        'download and every folder created is recorded.',
    'Os arquivos da sua pasta no FTP, para navegar, baixar e organizar.':
        'The files in your FTP folder, to browse, download and organize.',
    'Aqui você navega, baixa, cria pasta, troca o nome e apaga; enviar arquivo continua sendo feito '
    'por FTP. Apagar pede a sua senha do FTP e não tem lixeira. Todo download e toda alteração ficam '
    'registrados.':
        'Here you browse, download, create folders, rename and delete; uploading files is still done '
        'by FTP. Deleting asks for your FTP password and there is no recycle bin. Every download and '
        'every change is recorded.',
    'FTP sem TLS (texto puro), modo passivo':
        'FTP without TLS (plain text), passive mode',
    'FTPS explícito (FTP com TLS) ou, só para equipamento sem TLS, FTP em texto puro; modo passivo':
        'Explicit FTPS (FTP with TLS) or, only for devices without TLS, plain-text FTP; passive mode',
    'FTPS explícito (FTP com TLS), também no canal de dados; modo passivo':
        'Explicit FTPS (FTP with TLS), on the data channel too; passive mode',
    'Envio de arquivos':
        'File upload',
    'O caminho de cada arquivo':
        'The path of each file',
    'O equipamento envia':
        'The device sends',
    'por FTP, com o usuário e a senha desta conta':
        'by FTP, with the user name and password of this account',
    'O servidor recebe':
        'The server receives',
    'em uma área de entrada que é só desta conta':
        'in an inbox area that belongs to this account only',
    'O arquivo é guardado':
        'The file is stored',
    'na pasta do usuário, fora do alcance desta conta':
        'in the user folder, out of reach of this account',
    'Dados para enviar por FTP':
        'Details for sending by FTP',
    'Servidor':
        'Server',
    'Porta de controle':
        'Control port',
    'Portas passivas':
        'Passive ports',
    'Protocolo':
        'Protocol',
    'Usuário e senha':
        'User name and password',
    '<strong>{usuario}</strong>, com a mesma senha desta entrada':
        '<strong>{usuario}</strong>, with the same password used to sign in here',
    'O que esta conta faz':
        'What this account does',
    'Ela envia arquivo por FTP e mais nada. Cada arquivo que termina de chegar é guardado na pasta do '
    'usuário <strong>{usuario}</strong> no servidor, fora do alcance desta conta: ela não lista, não '
    'baixa, não renomeia e não apaga o que já enviou, nem por FTP nem por aqui.':
        'It uploads files by FTP and nothing else. Each file that finishes arriving is stored in the '
        'folder of the user <strong>{usuario}</strong> on the server, out of reach of this account: it '
        'does not list, download, rename or delete what it has already sent, by FTP or here.',
    'Depois de enviar, a pasta da sessão volta a ficar vazia: é o esperado. Arquivo enviado com um '
    'nome que já existe não substitui o anterior: o novo é guardado com a data e a hora no nome. Quem '
    'precisa conferir ou baixar o que foi enviado pede a um administrador ou usa uma conta de outro '
    'perfil.':
        'After an upload, the session folder goes back to empty: that is expected. A file sent with a '
        'name that already exists does not replace the previous one: the new file is stored with the '
        'date and time in its name. Whoever needs to check or download what was sent asks an '
        'administrator or uses an account with another profile.',
    'O que esta conta pode fazer':
        'What this account can do',
    'Esta conta só envia: o que chega fica guardado no servidor.':
        'This account only uploads: what arrives is kept on the server.',
    'FTPS explícito (FTP com TLS), modo passivo':
        'Explicit FTPS (FTP with TLS), passive mode',
    '<strong>IP público</strong>: alcançável pela internet se o firewall não barrar':
        '<strong>Public IP</strong>: reachable from the internet unless the firewall blocks it',
    '<strong>desligado</strong>: senhas e arquivos trafegam em texto puro. Só para equipamento sem '
    'suporte a TLS, em rede interna isolada.':
        '<strong>off</strong>: passwords and files travel in plain text. Only for devices without TLS '
        'support, on an isolated internal network.',
    'opcional: aceita login sem criptografia. Use só com equipamento legado.':
        'optional: accepts sign-in without encryption. Use only with legacy devices.',
    'obrigatório no login; os dados seguem o que o cliente pedir.':
        'required on sign-in; data follows what the client asks for.',
    'obrigatório no login e nos dados.':
        'required on sign-in and on data.',
    'modo desconhecido':
        'unknown mode',
    'IP privado, só o próprio host alcança':
        'Private IP, reachable only by the host itself',
    'IP privado, alcançável pela rede interna deste endereço':
        'Private IP, reachable from the internal network of this address',
    'O aviso do menu, do rodapé e do começo desta aba está oculto '
    '(<code>PAINEL_AVISO_EXPOSICAO=nao</code>).':
        'The notice in the menu, in the footer and at the top of this tab is hidden '
        '(<code>PAINEL_AVISO_EXPOSICAO=nao</code>).',
    'Endereço público':
        'Public address',
    'Painel por proxy ou túnel':
        'Panel behind a proxy or tunnel',
    'Endereço do FTP':
        'FTP address',
    'IP anunciado no modo passivo':
        'IP announced in passive mode',
    'TLS do FTP':
        'FTP TLS',
    'Certificado do FTP':
        'FTP certificate',
    'Endereço do painel':
        'Panel address',
    'Frente web':
        'Web front end',
    'O navegador fala com o nginx, a única porta publicada do painel: ele fecha o HTTPS, limita redes '
    'e taxa de pedidos e repassa por soquete Unix. O painel não escuta em porta de rede.':
        'The browser talks to nginx, the only published port of the panel: it terminates HTTPS, limits '
        'networks and request rate, and forwards over a Unix socket. The panel does not listen on any '
        'network port.',
    'Certificado do painel':
        'Panel certificate',
    'Quem pode abrir o painel':
        'Who can open the panel',
    'Sessão':
        'Session',
    'Encerra com {minutos} minutos sem uso e, de qualquer forma, em 8 horas. {falhas} entradas erradas '
    'bloqueiam o endereço por 15 minutos.':
        'Closes after {minutos} minutes without use and, in any case, after 8 hours. {falhas} wrong '
        'sign-ins block the address for 15 minutes.',
    'Entrada dos usuários do FTP':
        'Sign-in of FTP users',
    'Bloqueio por tentativa no FTP':
        'Blocking by attempts on FTP',
    'Bloqueio por endereço':
        'Blocking by address',
    'Custo das senhas do FTP':
        'Cost of FTP passwords',
    'Contato de segurança':
        'Security contact',
    'Container do painel':
        'Panel container',
    'Firewall do host':
        'Host firewall',
    'Segurança':
        'Security',
    '<strong>Exceção por usuário ligada</strong> (<code>FTP_TLS_EXCECOES=sim</code>): {quantos} '
    'usuário(s) entram sem TLS, com senha e arquivos em texto puro: {nomes}. Quem tenta entrar sem TLS '
    'sem estar dispensado é recusado, mas a senha já passou em texto puro: o log do FTP registra a '
    'tentativa.':
        '<strong>Per-user exception on</strong> (<code>FTP_TLS_EXCECOES=sim</code>): {quantos} user(s) '
        'sign in without TLS, with password and files in plain text: {nomes}. Whoever tries to sign in '
        'without TLS without being exempted is refused, but the password has already travelled in '
        'plain text: the FTP log records the attempt.',
    'Exceção por usuário ligada (<code>FTP_TLS_EXCECOES=sim</code>), sem nenhum usuário dispensado: '
    'todos entram com TLS, e a sessão sem TLS é recusada antes de a senha ser enviada. A dispensa de '
    'um equipamento sem suporte a TLS é feita em <a href="/usuarios">Usuários</a>.':
        'Per-user exception on (<code>FTP_TLS_EXCECOES=sim</code>), with no user exempted: everyone '
        'signs in with TLS, and a session without TLS is refused before the password is sent. '
        'Exempting a device without TLS support is done under <a href="/usuarios">Users</a>.',
    'Sem exceção por usuário: {motivo}.':
        'No per-user exception: {motivo}.',
    'Recusado por código (<code>REDE_PERMITIR_IP_PUBLICO=nao</code>): FTP e painel só escutam em IP '
    'privado. Aceitar é opção de quem instala.':
        'Refused by the code (<code>REDE_PERMITIR_IP_PUBLICO=nao</code>): FTP and panel listen only on '
        'private IPs. Accepting it is a choice of whoever installs.',
    'Não usado (<code>PAINEL_PROXY_CONFIAVEL</code> vazio): o endereço do cliente é sempre o da '
    'conexão, e <code>X-Forwarded-For</code> é ignorado. Publicar só o painel por proxy ou túnel é '
    'opção de quem instala.':
        'Not used (<code>PAINEL_PROXY_CONFIAVEL</code> empty): the client address is always the one of '
        'the connection, and <code>X-Forwarded-For</code> is ignored. Publishing only the panel '
        'through a proxy or tunnel is a choice of whoever installs.',
    'Clientes de <code>{redes}</code>; os demais são recusados pelo nginx, antes de chegar ao painel.':
        'Clients from <code>{redes}</code>; the others are refused by nginx, before reaching the panel.',
    'Desligada (<code>PAINEL_ACESSO_USUARIOS_FTP=nao</code>): só administrador entra no painel.':
        'Off (<code>PAINEL_ACESSO_USUARIOS_FTP=nao</code>): only administrators sign in to the panel.',
    '<strong>{quantos} usuário(s) com a senha gravada com o custo anterior</strong>: {nomes}. Cada '
    'tentativa de entrada com esses nomes ocupa mais o processador do FTP. O custo atual passa a valer '
    'quando a senha é trocada, na aba Usuários.':
        '<strong>{quantos} user(s) with the password stored with the previous cost</strong>: {nomes}. '
        'Each sign-in attempt with these names uses more of the FTP processor. The current cost '
        'applies once the password is changed, on the Users tab.',
    'Todas as senhas estão gravadas com o custo do porte atual (<code>FTP_MAX_CLIENTS</code>).':
        'All passwords are stored with the cost of the current sizing (<code>FTP_MAX_CLIENTS</code>).',
    'Publicado em <code>/.well-known/security.txt</code>: quem achar uma falha nesta instalação '
    'escreve para <code>{contato}</code>.':
        'Published at <code>/.well-known/security.txt</code>: whoever finds a flaw in this '
        'installation writes to <code>{contato}</code>.',
    'O painel não enxerga o firewall. Confira você: as portas do FTP e do painel devem estar liberadas '
    'só para os endereços que precisam, na cadeia <code>DOCKER-USER</code>':
        'The panel cannot see the firewall. Check it yourself: the FTP and panel ports must be open '
        'only to the addresses that need them, in the <code>DOCKER-USER</code> chain',
    '<strong>Aceito</strong> (<code>REDE_PERMITIR_IP_PUBLICO=sim</code>): a proteção contra a internet '
    'passa a ser o firewall do servidor, o TLS obrigatório e as senhas geradas.':
        '<strong>Accepted</strong> (<code>REDE_PERMITIR_IP_PUBLICO=sim</code>): protection against the '
        'internet now relies on the server firewall, mandatory TLS and generated passwords.',
    '<strong>Em uso</strong> (<code>PAINEL_PROXY_CONFIAVEL={proxies}</code>): o endereço de quem '
    'acessa é o que o proxy informa em <code>X-Forwarded-For</code>, e é ele que conta as senhas '
    'erradas, prende a sessão e vai para a auditoria. Quem pode chegar à tela de entrada é decidido no '
    'proxy ou no túnel. O FTP não passa por ele.':
        '<strong>In use</strong> (<code>PAINEL_PROXY_CONFIAVEL={proxies}</code>): the address of '
        'whoever connects is the one the proxy reports in <code>X-Forwarded-For</code>, and that is '
        'the address that counts wrong passwords, binds the session and goes to the audit log. Who can '
        'reach the sign-in screen is decided at the proxy or the tunnel. FTP does not go through it.',
    'IP privado.':
        'Private IP.',
    '<strong>IP público</strong>.':
        '<strong>Public IP</strong>.',
    'Modo':
        'Mode',
    'só HTTPS':
        'HTTPS only',
    '<strong>Bloqueado agora: {nomes}.</strong>':
        '<strong>Blocked now: {nomes}.</strong>',
    'Nenhum usuário bloqueado agora.':
        'No user blocked right now.',
    'Nenhum endereço bloqueado agora.':
        'No address blocked right now.',
    'Não publicado (<code>SEGURANCA_CONTATO_EMAIL</code> vazio): quem achar uma falha nesta instalação '
    'não tem para onde escrever.':
        'Not published (<code>SEGURANCA_CONTATO_EMAIL</code> empty): whoever finds a flaw in this '
        'installation has nowhere to write to.',
    'Raiz somente leitura':
        'Read-only root',
    'Raiz gravável: confira o <code>read_only</code>':
        'Writable root: check <code>read_only</code>',
    'Resumo da conferência':
        'Check summary',
    '{quantos} itens conferidos':
        '{quantos} items checked',
    'Confira a impressão digital com a que o navegador e o cliente FTP mostram antes de aceitar o '
    'certificado.':
        'Compare the fingerprint with the one the browser and the FTP client show before accepting the '
        'certificate.',
    '<strong>Rede pública na lista: {redes}.</strong>':
        '<strong>Public network in the list: {redes}.</strong>',
    'Ligada (<code>PAINEL_ACESSO_USUARIOS_FTP=sim</code>): cada usuário do FTP entra com o nome e a '
    'senha do FTP e só navega e baixa na pasta dele. Quem confere a senha é o próprio servidor FTP, '
    'pela rede interna da stack,':
        'On (<code>PAINEL_ACESSO_USUARIOS_FTP=sim</code>): each FTP user signs in with the FTP user '
        'name and password and only browses and downloads in their own folder. The FTP server itself '
        'checks the password, over the internal network of the stack,',
    '<strong>em texto puro</strong>, porque o FTP está sem TLS.':
        '<strong>in plain text</strong>, because FTP has no TLS.',
    'em TLS e com o certificado dele conferido.':
        'over TLS and with its certificate verified.',
    'O limite próprio de cada usuário fica em Editar, na aba Usuários.':
        'The limit of each user is under Edit, on the Users tab.',
    'O endereço que passa de {erros} de usuário e senha em {horas}, no FTP ou no painel, fica {dias} '
    'sem entrar nos dois (<code>BLOQUEIO_ENDERECO_ERROS</code>, <code>BLOQUEIO_ENDERECO_HORAS</code> e '
    '<code>BLOQUEIO_ENDERECO_DIAS</code>).':
        'An address with more than {erros} in user name and password within {horas}, on FTP or on the '
        'panel, is kept out of both for {dias} (<code>BLOQUEIO_ENDERECO_ERROS</code>, '
        '<code>BLOQUEIO_ENDERECO_HORAS</code> and <code>BLOQUEIO_ENDERECO_DIAS</code>).',
    '<strong>Desligado na stack</strong> (<code>BLOQUEIO_ENDERECO_ERROS=0</code>): nenhum endereço é '
    'bloqueado sozinho.':
        '<strong>Off in the stack</strong> (<code>BLOQUEIO_ENDERECO_ERROS=0</code>): no address is '
        'blocked automatically.',
    'e sem acesso ao Docker do host.':
        "and no access to the host's Docker.",
    '<strong>Há um socket do Docker montado: remova.</strong>':
        '<strong>A Docker socket is mounted: remove it.</strong>',
    '<strong>Com endereço público aceito, é o firewall que separa a stack da internet.</strong>':
        '<strong>With a public address accepted, the firewall is what separates the stack from the '
        'internet.</strong>',
    'e nenhuma delas pode ser redirecionada da internet.':
        'and none of them may be forwarded from the internet.',
    'O que protege o servidor nesta instalação, conferido agora.':
        'What protects the server on this installation, checked just now.',
    '{n} endereço bloqueado agora':
        '{n} address blocked now',
    '{n} endereços bloqueados agora':
        '{n} addresses blocked now',
    '<strong>Com endereço público aceito, preencha.</strong>':
        '<strong>With a public address accepted, fill it in.</strong>',
    '{tentativas} senhas erradas do mesmo endereço bloqueiam o usuário para aquele endereço por '
    '{minutos} minutos (<code>FTP_BLOQUEIO_TENTATIVAS</code> e <code>FTP_BLOQUEIO_MINUTOS</code>).':
        '{tentativas} wrong passwords from the same address block the user for that address for '
        '{minutos} minutes (<code>FTP_BLOQUEIO_TENTATIVAS</code> and '
        '<code>FTP_BLOQUEIO_MINUTOS</code>).',
    '<strong>Desligado na stack</strong> (<code>FTP_BLOQUEIO_TENTATIVAS=0</code>): só é bloqueado o '
    'usuário que tem limite próprio.':
        '<strong>Off in the stack</strong> (<code>FTP_BLOQUEIO_TENTATIVAS=0</code>): only users with '
        'their own limit are blocked.',
    'em ordem':
        'in order',
    'pedem atenção':
        'need attention',
    'com problema':
        'with a problem',
    'que o painel não confere ou não se aplicam':
        'that the panel does not check or that do not apply',
    '{parte} de {todo}':
        '{parte} of {todo}',
    'Cada container lê o próprio uso e os limites que recebeu no <code>compose.yaml</code> '
    '(<code>*_CPU_LIMIT</code>, <code>*_MEMORY_LIMIT</code> e <code>*_PIDS_LIMIT</code> no '
    '<code>.env</code>), sem swap; a memória em uso não conta o cache de arquivo que o sistema solta '
    'quando precisa. O histórico guarda os últimos {periodo}, com uma leitura a cada {intervalo} s, e '
    'recomeça quando o painel reinicia; cada desenho vai de zero até pouco acima do pico do período. '
    'Na rede, a linha cheia é o que chega e a tracejada, o que sai, e os totais contam desde que o '
    'serviço do FTP iniciou; o disco é o da pasta dos dados.':
        'Each container reads its own usage and the limits it received in <code>compose.yaml</code> '
        '(<code>*_CPU_LIMIT</code>, <code>*_MEMORY_LIMIT</code> and <code>*_PIDS_LIMIT</code> in '
        '<code>.env</code>), without swap; memory in use does not count the file cache that the system '
        'releases when needed. The history keeps the last {periodo}, with one reading every '
        '{intervalo} s, and starts over when the panel restarts; each chart goes from zero to just '
        'above the peak of the period. On the network, the solid line is what arrives and the dashed '
        'one is what leaves, and the totals count from when the FTP service started; the disk is the '
        'one holding the data folder.',
    'nunca':
        'never',
    'Servidor FTP':
        'FTP server',
    'Painel':
        'Panel',
    'do servidor (sem limite)':
        'of the server (no limit)',
    'Memória':
        'Memory',
    '{parte} de {todo} em uso':
        '{parte} of {todo} in use',
    'Processador':
        'CPU',
    'o servidor não tem':
        'the server has none',
    'Disco':
        'Disk',
    'Rede do FTP':
        'FTP network',
    'recebendo e enviando agora':
        'receiving and sending now',
    'A tela se atualiza a cada {segundos} s. A atualização automática não conta como uso do painel: a '
    'sessão encerra depois de {minutos} min sem ação sua.':
        'The screen refreshes every {segundos} s. Automatic refresh does not count as use of the '
        'panel: the session closes after {minutos} min without any action from you.',
    'Para acompanhar sem recarregar a página, ligue <strong>Atualizar sozinha</strong>.':
        'To follow along without reloading the page, turn on <strong>Auto-refresh</strong>.',
    'últimos {tempo}':
        'last {tempo}',
    'Fora do ar':
        'Down',
    'Processos':
        'Processes',
    'processador, pico de {pico}%':
        'CPU, peak of {pico}%',
    'Alocado aos {quantos} containers: <strong>{nucleos}</strong> e <strong>{memoria}</strong> de '
    'memória':
        'Allocated to the {quantos} containers: <strong>{nucleos}</strong> and '
        '<strong>{memoria}</strong> of memory',
    'em uso agora: <strong>{nucleos}</strong> e <strong>{memoria}</strong>':
        'in use now: <strong>{nucleos}</strong> and <strong>{memoria}</strong>',
    'em uso agora: <strong>{memoria}</strong>':
        'in use now: <strong>{memoria}</strong>',
    'o servidor tem {nucleos} e {memoria}':
        'the server has {nucleos} and {memoria}',
    'nenhum':
        'none',
    'desligado na stack':
        'off in the stack',
    'Containers da stack':
        'Stack containers',
    'O painel não conseguiu ler o uso do processador neste servidor.':
        'The panel could not read the CPU usage on this server.',
    'O painel não conseguiu ler a memória deste servidor.':
        'The panel could not read the memory of this server.',
    '(soma incompleta: há pasta grande demais para ser lida inteira)':
        '(incomplete sum: there is a folder too large to be read in full)',
    'O serviço do FTP ainda não publicou a leitura da rede dele. Ela aparece alguns segundos depois de '
    'ele iniciar.':
        'The FTP service has not published its network reading yet. It shows up a few seconds after '
        'the service starts.',
    'lendo':
        'reading',
    'topo em {velocidade}':
        'top at {velocidade}',
    'Processador do servidor':
        'Server CPU',
    'Memória do servidor':
        'Server memory',
    'sem leitura':
        'no reading',
    'Processador dos containers':
        'Container CPU',
    'Memória dos containers':
        'Container memory',
    'Servidor e containers':
        'Server and containers',
    'ver o servidor':
        'see the server',
    'núcleos':
        'cores',
    'núcleo':
        'core',
    'O histórico aparece alguns segundos depois de o painel iniciar.':
        'The history shows up a few seconds after the panel starts.',
    'No ar':
        'Up',
    'sem leitura: ela aparece alguns segundos depois de o container iniciar':
        'no reading: it shows up a few seconds after the container starts',
    '{quantos} em vigor':
        '{quantos} active',
    'pico de {pico}%':
        'peak of {pico}%',
    'Média de 1 min':
        '1 min average',
    'Carga média':
        'Load average',
    'Ligado há':
        'Uptime',
    'Modelo':
        'Model',
    'Disponível':
        'Available',
    'Em cache':
        'Cached',
    'O painel não conseguiu ler o disco da pasta dos dados.':
        'The panel could not read the disk holding the data folder.',
    'Livre':
        'Free',
    'Pico recebendo':
        'Peak receiving',
    'Pico enviando':
        'Peak sending',
    'Total recebido':
        'Total received',
    'Total enviado':
        'Total sent',
    'Erros e descartes':
        'Errors and drops',
    'Sem tráfego há':
        'No traffic for',
    'Parar a atualização':
        'Stop refreshing',
    'Atualizar sozinha':
        'Auto-refresh',
    'vez':
        'time',
    'vezes':
        'times',
    'Memória no limite':
        'Memory at the limit',
    'de {todo}':
        'of {todo}',
    'sem limite':
        'no limit',
    'no ar há {tempo}':
        'up for {tempo}',
    'Bloqueios de entrada':
        'Sign-in blocks',
    'a primeira leitura sai em alguns segundos':
        'the first reading comes in a few seconds',
    'Outros dados':
        'Other data',
    'Recursos do servidor':
        'Server resources',
    'A máquina inteira, e não só o que a stack usa dela.':
        'The whole machine, not only what the stack uses of it.',
    'Lido às {hora}.':
        'Read at {hora}.',
    'Atenção':
        'Attention',
    'Pastas do FTP':
        'FTP folders',
    'Os containers desta stack e o servidor em que ela roda.':
        'The containers of this stack and the server it runs on.',
    'Como estas medidas são lidas':
        'How these measurements are read',
    'Limite de processador atingido':
        'CPU limit reached',
    'Encerrado por falta de memória':
        'Killed for lack of memory',
    'Sessões de administrador':
        'Administrator sessions',
    'Certificado':
        'Certificate',
    'A senha e os arquivos deste usuário passam a trafegar em texto puro e podem ser lidos por quem '
    'estiver na mesma rede. Use só para equipamento antigo sem suporte a TLS, em rede interna isolada, '
    'com o firewall liberando só esse equipamento. Os outros usuários continuam obrigados a usar TLS.':
        'The password and the files of this user will travel in plain text and can be read by anyone '
        'on the same network. Use it only for old devices without TLS support, on an isolated internal '
        'network, with the firewall allowing only that device. The other users are still required to '
        'use TLS.',
    'Usuário criado.':
        'User created.',
    'Usuário criado e dispensado do TLS: a senha e os arquivos dele passam em texto puro.':
        'User created and exempted from TLS: their password and files travel in plain text.',
    'Usuário criado, mas a dispensa do TLS não foi gravada: ele só entra com TLS. Tente de novo em '
    'Editar.':
        'User created, but the TLS exemption was not saved: they only sign in with TLS. Try again '
        'under Edit.',
    'Senha trocada.':
        'Password changed.',
    'Pasta trocada. Os arquivos da pasta anterior continuam nela.':
        'Folder changed. The files of the previous folder stay in it.',
    'Perfil trocado. Vale na próxima entrada do usuário no FTP.':
        "Profile changed. It applies on the user's next FTP sign-in.",
    'Limites gravados. Valem na próxima entrada do usuário no FTP.':
        "Limits saved. They apply on the user's next FTP sign-in.",
    'Bloqueio removido. O usuário volta a poder entrar no FTP.':
        'Block removed. The user can sign in to FTP again.',
    'Usuário removido. Os arquivos continuam na pasta.':
        'User removed. The files stay in the folder.',
    'Usuário removido e pasta apagada.':
        'User removed and folder deleted.',
    'Usuário dispensado do TLS: a senha e os arquivos dele passam em texto puro.':
        'User exempted from TLS: their password and files travel in plain text.',
    'O usuário volta a ser obrigado a usar TLS.':
        'The user is required to use TLS again.',
    'Administrador criado.':
        'Administrator created.',
    'Senha trocada. As outras sessões desse administrador foram encerradas.':
        'Password changed. The other sessions of this administrator were closed.',
    'Nome trocado. As outras sessões desse administrador foram encerradas.':
        'Name changed. The other sessions of this administrator were closed.',
    'Administrador removido. As sessões dele foram encerradas.':
        'Administrator removed. Their sessions were closed.',
    'Pasta <span class="suave">(deixe em branco para usar o nome do usuário)</span>':
        'Folder <span class="suave">(leave blank to use the user name)</span>',
    'Usuário não encontrado':
        'User not found',
    'Dispensar um usuário do TLS não está disponível nesta instalação: {motivo}. Quem muda isso é quem '
    'administra o servidor, no <code>.env</code>, com <code>./deploy.sh</code> em seguida.':
        'Exempting a user from TLS is not available on this installation: {motivo}. Whoever manages '
        'the server changes that, in <code>.env</code>, followed by <code>./deploy.sh</code>.',
    'Administrador':
        'Administrator',
    'entra no painel e administra tudo; não é conta do FTP':
        'signs in to the panel and manages everything; not an FTP account',
    'Completo':
        'Full',
    'envia, baixa, renomeia e apaga':
        'uploads, downloads, renames and deletes',
    'Envio':
        'Upload',
    'envia e baixa; não apaga nem altera o que já enviou':
        'uploads and downloads; does not delete or change what was already sent',
    'Só envio':
        'Upload only',
    'só envia; não lista nem baixa nada, nem o que ela mesma enviou':
        'only uploads; does not list or download anything, not even what it sent itself',
    'Leitura':
        'Read only',
    'só lista e baixa':
        'only lists and downloads',
    'Pasta inválida. Veja a regra abaixo do campo.':
        'Invalid folder. See the rule below the field.',
    'vazio: {padrao}, o padrão da stack':
        'empty: {padrao}, the stack default',
    'vazio: o padrão da stack, que está desligado':
        'empty: the stack default, which is off',
    'na pasta dele':
        'in their folder',
    'TLS por usuário sem efeito':
        'Per-user TLS has no effect',
    'Senhas erradas demais no FTP, vindas de: {origens}':
        'Too many wrong passwords on FTP, coming from: {origens}',
    'Usuários':
        'Users',
    'Senha':
        'Password',
    '(deixe em branco para o painel gerar uma senha forte)':
        '(leave blank for the panel to generate a strong password)',
    'Repita a senha':
        'Repeat the password',
    'Mínimo de {minimo} caracteres. A senha gerada aparece uma única vez, na tela seguinte.':
        'Minimum of {minimo} characters. The generated password is shown only once, on the next screen.',
    'As duas senhas não são iguais.':
        'The two passwords do not match.',
    'A senha deve ter de {minimo} a {maximo} caracteres.':
        'The password must have {minimo} to {maximo} characters.',
    'A senha não pode ter caractere de controle.':
        'The password cannot contain control characters.',
    'Fica dentro de <code>{pasta}</code> e é criada se não existir. Até 4 níveis separados por '
    '<code>/</code>; letras, números, <code>_</code>, <code>-</code> e ponto; nenhum nível começa com '
    'ponto.':
        'It stays inside <code>{pasta}</code> and is created if it does not exist. Up to 4 levels '
        'separated by <code>/</code>; letters, digits, <code>_</code>, <code>-</code> and dot; no '
        'level starts with a dot.',
    'Usuários com a mesma pasta, ou com uma dentro da outra, alcançam os arquivos um do outro, cada um '
    'até onde o perfil dele deixa. Para um equipamento não alcançar o backup de outro, dê a cada um a '
    'própria pasta.':
        "Users with the same folder, or with one inside the other, reach each other's files, each one "
        "as far as their profile allows. To keep one device from reaching another's backup, give each "
        'one its own folder.',
    'Equipamento sem suporte a TLS: deixar este usuário entrar <strong>sem TLS</strong>':
        'Device without TLS support: let this user sign in <strong>without TLS</strong>',
    'Sem marcar a caixa, o usuário só entra com TLS (FTPS explícito).':
        'With the box unticked, the user only signs in with TLS (explicit FTPS).',
    'Novo usuário':
        'New user',
    'Limites':
        'Limits',
    'Campo vazio quer dizer <strong>sem limite próprio</strong>: vale o da stack.':
        'An empty field means <strong>no limit of its own</strong>: the stack limit applies.',
    'Horário em que o FTP aceita a entrada: das':
        'Hours when FTP accepts sign-in: from',
    'até as':
        'to',
    'Os limites valem na próxima entrada do usuário no FTP. Quando um limite do FTP muda, a sessão '
    'dele no painel é encerrada. Quem confere a senha do painel é o FTP: fora do horário, ou com todas '
    'as sessões dele ocupadas, o usuário também não entra no painel.':
        "The limits apply on the user's next FTP sign-in. When an FTP limit changes, their panel "
        'session is closed. FTP is what checks the panel password: outside the hours, or with all '
        'their sessions taken, the user cannot sign in to the panel either.',
    'O bloqueio vale só para este usuário e só para o endereço que errou a senha: os outros endereços '
    'e a entrada dele pelo painel continuam valendo. Entrada certa zera a contagem. Entrada fora do '
    'horário conta como senha errada. Equipamentos que chegam ao FTP pelo mesmo endereço são '
    'bloqueados juntos. Mudar um destes dois campos tira os bloqueios do usuário.':
        'The block applies only to this user and only to the address that got the password wrong: the '
        'other addresses and their sign-in through the panel keep working. A correct sign-in resets '
        'the count. A sign-in outside the hours counts as a wrong password. Devices that reach FTP '
        'through the same address are blocked together. Changing either of these two fields removes '
        "the user's blocks.",
    'Gravar limites':
        'Save limits',
    'Nenhum bloqueio em vigor.':
        'No block in effect.',
    'O FTP está recusando este usuário quando ele chega dos endereços abaixo, por senhas erradas '
    'demais. Com a senha certa ele também é recusado, até o fim do prazo.':
        'FTP is refusing this user when they come from the addresses below, for too many wrong '
        'passwords. With the right password they are refused as well, until the period ends.',
    'Perfil':
        'Profile',
    'O perfil vale no FTP e na entrada do usuário pelo painel. A troca vale no próximo login no FTP e '
    'encerra a sessão dele no painel; sessão de FTP que já está aberta segue com o perfil anterior até '
    'sair.':
        "The profile applies on FTP and on the user's sign-in to the panel. The change applies on the "
        'next FTP login and closes their panel session; an FTP session that is already open keeps the '
        'previous profile until it ends.',
    'No perfil Envio, o arquivo passa a ser do servidor assim que termina de chegar: daí em diante o '
    'usuário não o apaga, não o renomeia e não grava por cima. Equipamento que envia sempre com o '
    'mesmo nome de arquivo precisa do perfil Completo.':
        'With the Upload profile, the file belongs to the server as soon as it finishes arriving: from '
        'then on the user does not delete it, rename it or write over it. A device that always uploads '
        'with the same file name needs the Full profile.',
    'No perfil Só envio, a conta entra em uma área de entrada vazia e cada arquivo que chega é movido '
    'para a pasta do usuário: ela não lista nem baixa o que está lá. Nome repetido não substitui o '
    'anterior: o novo é guardado com a data e a hora no nome. Equipamento que envia com um nome '
    'provisório e renomeia no fim, ou que confere o envio listando a pasta, precisa de outro perfil.':
        'With the Upload only profile, the account lands in an empty inbox area and each file that '
        'arrives is moved to the user folder: it does not list or download what is there. A repeated '
        'name does not replace the previous one: the new file is stored with the date and time in its '
        'name. A device that uploads with a temporary name and renames at the end, or that checks the '
        'upload by listing the folder, needs another profile.',
    'Gravar perfil':
        'Save profile',
    'Este usuário só entra com <strong>TLS</strong> (FTPS explícito).':
        'This user only signs in with <strong>TLS</strong> (explicit FTPS).',
    'Dispensar TLS':
        'Exempt from TLS',
    'Para equipamento antigo sem suporte a TLS, em rede interna isolada. A tela seguinte pede a '
    'confirmação.':
        'For old devices without TLS support, on an isolated internal network. The next screen asks '
        'for confirmation.',
    'Também alcançada por: <strong>{outros}</strong>.':
        'Also reached by: <strong>{outros}</strong>.',
    'Editar usuário':
        'Edit user',
    'Remover usuário':
        'Remove user',
    'Exigir TLS':
        'Require TLS',
    'Sim, voltar a exigir o TLS':
        'Yes, require TLS again',
    'Sim, deixar este usuário entrar sem TLS':
        'Yes, let this user sign in without TLS',
    'Também alcançada por: {outros}':
        'Also reached by: {outros}',
    'Editar':
        'Edit',
    'Remover':
        'Remove',
    'Nenhum usuário ainda.':
        'No users yet.',
    'Dispensado do TLS pelo administrador, em Editar ou ao criar: a senha e os arquivos desse usuário '
    'trafegam em texto puro.':
        'Exempted from TLS by the administrator, under Edit or on creation: the password and the files '
        'of this user travel in plain text.',
    'Perfil inválido.':
        'Invalid profile.',
    'Já existe um usuário com este nome.':
        'There is already a user with this name.',
    'Sessões ao mesmo tempo no FTP':
        'Simultaneous FTP sessions',
    'conexões abertas com este usuário':
        'open connections with this user',
    'Taxa de download, em KB por segundo':
        'Download rate, in KB per second',
    'no FTP e nos downloads dele pelo painel':
        'on FTP and on their downloads through the panel',
    'Taxa de envio, em KB por segundo':
        'Upload rate, in KB per second',
    'no FTP; cada arquivo enviado leva pelo menos 256 ÷ taxa segundos':
        'on FTP; each uploaded file takes at least 256 ÷ rate seconds',
    'Downloads ao mesmo tempo pelo painel':
        'Simultaneous downloads through the panel',
    'vazio: {padrao}':
        'empty: {padrao}',
    'Senhas erradas no FTP até o bloqueio':
        'Wrong FTP passwords before the block',
    '{padrao}; 0: este usuário nunca é bloqueado':
        '{padrao}; 0: this user is never blocked',
    'Minutos de bloqueio':
        'Minutes of block',
    'vazio: {padrao}, o padrão da stack; é também o tempo em que as senhas erradas se somam':
        'empty: {padrao}, the stack default; it is also the time over which wrong passwords add up',
    'Este usuário segue o <code>FTP_TLS_MODE</code>, como todos os outros.':
        'This user follows <code>FTP_TLS_MODE</code>, like all the others.',
    'Este usuário entra <strong>sem TLS</strong>: a senha e os arquivos dele trafegam em texto puro e '
    'podem ser lidos por quem estiver na mesma rede. Com TLS ele continua entrando normalmente.':
        'This user signs in <strong>without TLS</strong>: their password and files travel in plain '
        'text and can be read by anyone on the same network. With TLS they still sign in normally.',
    'Volte a exigir assim que o equipamento tiver suporte a TLS, e troque a senha em seguida.':
        'Require it again as soon as the device supports TLS, and change the password right after.',
    'fora da pasta dos dados':
        'outside the data folder',
    'inicial':
        'initial',
    'Este já é o perfil do usuário.':
        "This is already the user's profile.",
    'Este é o usuário inicial. A senha trocada aqui vale até o arquivo '
    '<code>.secrets/ftp-usuario-inicial-senha.txt</code> ser alterado: aí, na subida seguinte do '
    'serviço <code>ftp</code>, volta a valer a do arquivo.':
        'This is the initial user. The password changed here is valid until the file '
        '<code>.secrets/ftp-usuario-inicial-senha.txt</code> is changed: then, on the next start of '
        'the <code>ftp</code> service, the one in the file applies again.',
    'Esta pasta também é alcançada por: <strong>{outros}</strong>. Por isso ela não é apagada junto '
    'com o usuário: os arquivos continuam nela.':
        'This folder is also reached by: <strong>{outros}</strong>. That is why it is not deleted '
        'together with the user: the files stay in it.',
    'Este é o usuário inicial, criado pela instalação. Removido, ele não volta nas próximas subidas do '
    'serviço <code>ftp</code>; para tê-lo de novo, crie um usuário com o mesmo nome.':
        'This is the initial user, created by the installation. Once removed, it does not come back on '
        'the next starts of the <code>ftp</code> service; to have it again, create a user with the '
        'same name.',
    'A senha dele já trafegou em texto puro: troque-a depois de exigir o TLS.':
        'Their password has already travelled in plain text: change it after requiring TLS.',
    'Com TLS este usuário continua entrando normalmente. Dê a ele uma pasta só dele e uma senha que '
    'não seja usada em mais nenhum lugar. A dispensa vale em instantes; as sessões em andamento no FTP '
    'não são interrompidas.':
        'With TLS this user still signs in normally. Give them a folder of their own and a password '
        'that is not used anywhere else. The exemption takes effect in moments; FTP sessions in '
        'progress are not interrupted.',
    'você':
        'you',
    'Painel inteiro; {n} sessão aberta':
        'Whole panel; {n} open session',
    'Painel inteiro; {n} sessões abertas':
        'Whole panel; {n} open sessions',
    'Abrir na aba Arquivos':
        'Open on the Files tab',
    'Criado pela instalação, uma vez; removido, não volta sozinho':
        'Created by the installation, once; if removed, it does not come back on its own',
    'Limites próprios: {limites}':
        'Own limits: {limites}',
    'limites':
        'limits',
    'bloqueado':
        'blocked',
    'Pasta':
        'Folder',
    'Uso':
        'Usage',
    'Último envio':
        'Last upload',
    '<strong>Administrador</strong> entra neste painel e administra tudo; não é conta do FTP. Alterar '
    'administrador pede a sua senha atual, e ninguém remove a própria conta. Até {maximo} '
    'administradores.':
        '<strong>Administrator</strong> signs in to this panel and manages everything; not an FTP '
        'account. Changing an administrator asks for your current password, and nobody removes their '
        'own account. Up to {maximo} administrators.',
    '<strong>Completo</strong> envia, baixa, renomeia e apaga. <strong>Envio</strong> envia e baixa, '
    'sem apagar nem alterar o que já enviou. <strong>Só envio</strong> só envia: não lista nem baixa '
    'nada. <strong>Leitura</strong> só lista e baixa. O perfil vale no FTP e na entrada do usuário '
    'pelo painel.':
        '<strong>Full</strong> uploads, downloads, renames and deletes. <strong>Upload</strong> '
        'uploads and downloads, without deleting or changing what was already sent. <strong>Upload '
        'only</strong> only uploads: it does not list or download anything. <strong>Read only</strong> '
        "only lists and downloads. The profile applies on FTP and on the user's sign-in to the panel.",
    'Cada usuário do FTP fica preso na pasta dele, dentro de <code>{pasta}</code> no servidor. Toda '
    'alteração vale no próximo login, sem reiniciar o FTP.':
        'Each FTP user is confined to their own folder, inside <code>{pasta}</code> on the server. '
        'Every change applies on the next login, without restarting FTP.',
    'Usuário e perfil':
        'User and profile',
    'Usuário <strong>{nome}</strong>. Senha gerada pelo painel:':
        'User <strong>{nome}</strong>. Password generated by the panel:',
    'Copie agora para o equipamento ou para o seu cofre de senhas. Ela <strong>não será mostrada de '
    'novo</strong> e não fica guardada em lugar nenhum além do hash do FTP.':
        'Copy it now to the device or to your password vault. It <strong>will not be shown '
        'again</strong> and is not kept anywhere besides the FTP hash.',
    'Nome do usuário':
        'User name',
    'Criar usuário':
        'Create user',
    'O que este usuário pode fazer':
        'What this user can do',
    'Usuário <strong>{nome}</strong>{inicial}. O nome não muda: é com ele que o equipamento entra no '
    'FTP.':
        'User <strong>{nome}</strong>{inicial}. The name does not change: it is what the device uses '
        'to sign in to FTP.',
    'Pasta atual: {onde}, com {arquivos} arquivo(s), {tamanho}.':
        'Current folder: {onde}, with {arquivos} file(s), {tamanho}.',
    'Os arquivos da pasta atual <strong>não são movidos nem apagados</strong>: continuam onde estão, e '
    'o usuário deixa de alcançá-los. A troca vale no próximo login no FTP e encerra a sessão dele no '
    'painel.':
        'The files in the current folder <strong>are not moved or deleted</strong>: they stay where '
        'they are, and the user no longer reaches them. The change applies on the next FTP login and '
        'closes their panel session.',
    'Trocar pasta':
        'Change folder',
    'Esta já é a pasta do usuário.':
        "This is already the user's folder.",
    'Usuário <strong>{nome}</strong>. A senha antiga deixa de valer no próximo login.':
        'User <strong>{nome}</strong>. The old password stops working on the next login.',
    'Apagar também a pasta e tudo o que há nela':
        'Also delete the folder and everything in it',
    'O painel <strong>não tem lixeira</strong>: a pasta apagada só volta de uma cópia de segurança. '
    'Sem marcar a caixa, os arquivos continuam em {onde}.':
        'The panel <strong>has no recycle bin</strong>: a deleted folder only comes back from a '
        'backup. With the box unticked, the files stay in {onde}.',
    'Remover <strong>{nome}</strong>? O login deixa de funcionar na hora.':
        'Remove <strong>{nome}</strong>? The login stops working immediately.',
    'A pasta dele tem {arquivos} arquivo(s), {tamanho}, em {onde}.':
        'Their folder has {arquivos} file(s), {tamanho}, in {onde}.',
    'Sim, remover o usuário':
        'Yes, remove the user',
    'A pasta deste usuário não pode ser apagada junto: outro usuário a alcança, ou ela fica fora da '
    'pasta dos dados. Nada foi alterado.':
        'The folder of this user cannot be deleted along with it: another user reaches it, or it is '
        'outside the data folder. Nothing was changed.',
    'Não foi possível remover:':
        'Could not remove:',
    'Não foi possível alterar:':
        'Could not change:',
    'dividida':
        'shared',
    'e outros':
        'and others',
    'sem TLS':
        'no TLS',
    'obrigatório':
        'required',
    'Pasta alcançada por mais de um usuário: cada um mexe nos arquivos do outro até onde o perfil dele '
    'deixa.':
        "Folder reached by more than one user: each one handles the other's files as far as their "
        'profile allows.',
    'Limite próprio, ajustado em Editar.':
        'Own limit, set under Edit.',
    'Recusado pelo FTP por senhas erradas demais vindas de um endereço: o bloqueio sai sozinho no fim '
    'do prazo, ou em Editar.':
        'Refused by FTP for too many wrong passwords coming from one address: the block goes away on '
        'its own when the period ends, or under Edit.',
    'As contas do painel e do FTP, cada uma com o seu perfil.':
        'The panel and FTP accounts, each with its profile.',
    'Como funcionam os perfis e as etiquetas':
        'How profiles and tags work',
    'Não foi possível criar:':
        'Could not create:',
    'Pasta nova':
        'New folder',
    'Não foi possível trocar:':
        'Could not change:',
    'Todos os usuários seguem o <code>FTP_TLS_MODE</code>.':
        'All users follow <code>FTP_TLS_MODE</code>.',
    'O usuário <strong>{nome}</strong> entra hoje <strong>sem TLS</strong>. Ao voltar a exigir, o '
    'equipamento dele só entra com TLS (FTPS explícito): confira antes se ele já foi configurado para '
    'isso.':
        'The user <strong>{nome}</strong> currently signs in <strong>without TLS</strong>. Once it is '
        'required again, their device only signs in with TLS (explicit FTPS): check first whether it '
        'has already been set up for that.',
    'Deixar <strong>{nome}</strong> entrar no FTP <strong>sem TLS</strong>?':
        'Let <strong>{nome}</strong> sign in to FTP <strong>without TLS</strong>?',
    'pedida para criar administrador':
        'required to create an administrator',
    'só para apagar a pasta':
        'only to delete the folder',
    'Como o servidor está agora e o que colocar no equipamento para ele enviar o backup.':
        'How the server is right now and what to set on the device for it to send the backup.',
    '{espaco} livres no disco':
        '{espaco} free on disk',
    'Sem TLS: texto puro':
        'No TLS: plain text',
    'TLS opcional: aceita texto puro':
        'Optional TLS: accepts plain text',
    'TLS obrigatório no login':
        'TLS required on sign-in',
    'TLS obrigatório no login e nos dados':
        'TLS required on sign-in and on data',
    'hoje':
        'today',
    'A contagem está incompleta: há pasta grande demais para ser lida inteira.':
        'The count is incomplete: there is a folder too large to be read in full.',
    'Arquivos recebidos por dia':
        'Files received per day',
    '<strong class="numero">{quantos}</strong> com data de {desde} até hoje, em todas as pastas':
        '<strong class="numero">{quantos}</strong> dated from {desde} until today, in all folders',
    'Conta o que está nas pastas agora, pela data de cada arquivo: o que foi apagado ou substituído '
    'não entra.':
        'It counts what is in the folders now, by the date of each file: what was deleted or replaced '
        'is not included.',
    'Último envio por usuário':
        'Last upload per user',
    'ver os usuários':
        'see the users',
    'Espaço por pasta':
        'Space per folder',
    'ver as pastas':
        'see the folders',
    'não lido':
        'not read',
    'não foi possível ler o certificado':
        'could not read the certificate',
    'vencido há {dias} dias':
        'expired {dias} days ago',
    'válido, faltam {dias} dias':
        'valid, {dias} days left',
    'Visão geral':
        'Overview',
    'arquivos':
        'files',
    'Nenhum usuário cadastrado. O primeiro é criado em <a href="/usuarios">Usuários</a>.':
        'No user registered. The first one is created under <a href="/usuarios">Users</a>.',
    'Nenhum usuário está há mais de 7 dias sem enviar.':
        'No user has gone more than 7 days without uploading.',
    'Nenhuma pasta de usuário ainda.':
        'No user folder yet.',
    'Sem enviar há mais de 7 dias':
        'No upload for more than 7 days',
    'As {maiores} maiores de {todas} pastas.':
        'The {maiores} largest of {todas} folders.',
    'Situação do servidor':
        'Server status',
    'conferir a segurança':
        'check the security',
    'contas cadastradas no FTP':
        'accounts registered on FTP',
    'Espaço usado':
        'Space used',
    'arquivo mais novo nas pastas':
        'newest file in the folders',
    'ver os arquivos':
        'see the files',
    'conferir a impressão digital':
        'check the fingerprint',
    'Atividade recente':
        'Recent activity',
    'ver toda a atividade':
        'see all activity',
    'Dados para configurar o equipamento':
        'Details to set up the device',
    'um usuário por equipamento ou por grupo, criado em <a href="/usuarios">Usuários</a>':
        'one user per device or per group, created under <a href="/usuarios">Users</a>',
    'e mais {resto}, na aba Usuários.':
        'and {resto} more, on the Users tab.',
    'nas últimas 24 horas':
        'in the last 24 hours',
    'entre 1 e 7 dias':
        'between 1 and 7 days',
    'há mais de 7 dias':
        'more than 7 days ago',
    'sem arquivo na pasta':
        'no file in the folder',
    '{quantos} arquivo':
        '{quantos} file',
    '{quantos} arquivos':
        '{quantos} files',
    'nenhum arquivo na pasta':
        'no file in the folder',
    'modo TLS {modo}':
        'TLS mode {modo}',
    'com exceção por usuário':
        'with per-user exception',
    'Envio sem tamanho declarado.':
        'Submission without a declared size.',
    'Envio grande demais.':
        'Submission too large.',
    'Formato de envio não aceito.':
        'Submission format not accepted.',
    'Idioma não aceito.':
        'Language not accepted.',
    'Não foi possível gravar o idioma.':
        'Could not save the language.',
    'Formulário sem token válido. Abra a página de novo e repita.':
        'Form without a valid token. Open the page again and repeat.',
    'Envio malformado.':
        'Malformed submission.',
    'cliente fora das redes permitidas':
        'client outside the allowed networks',
    'endereço bloqueado por excesso de erros de usuário e senha':
        'address blocked for too many user name and password errors',
    'endereço não aceito':
        'address not accepted',
    'O envio não partiu deste painel.':
        'The submission did not come from this panel.',
    'Não encontrado':
        'Not found',
    'Voltar ao painel':
        'Back to the panel',
    'pedido sem o endereço do cliente':
        'request without the client address',
    'contato de segurança não configurado':
        'security contact not configured',
    'Página não encontrada':
        'Page not found',
    'roteador':
        'router',
    'switch':
        'switch',
    'OLT':
        'OLT',
    'rádio':
        'radio',
    '/roteador':
        '/router',
    '/switch':
        '/switch',
    '/olt':
        '/olt',
    '/radio':
        '/radio',
    'Pausar movimento':
        'Pause motion',
    'Retomar movimento':
        'Resume motion',
    'a opção está desligada (<code>FTP_TLS_EXCECOES=nao</code>)':
        'the option is off (<code>FTP_TLS_EXCECOES=nao</code>)',
    'ela só vale com <code>FTP_TLS_MODE=2</code>, e o FTP está em outro modo':
        'it only applies with <code>FTP_TLS_MODE=2</code>, and FTP is in another mode',
    'ela não vale com <code>REDE_PERMITIR_IP_PUBLICO=sim</code>: FTP sem TLS na internet entrega a '
    'senha a quem escuta':
        'it does not apply with <code>REDE_PERMITIR_IP_PUBLICO=sim</code>: FTP without TLS on the '
        'internet hands the password to whoever is listening',
    '(a de {dono}, {para})':
        '(the one for {dono}, {para})',
    'Sua senha do FTP':
        'Your FTP password',
    'Sua senha atual':
        'Your current password',
    'Muitas tentativas. Aguarde alguns minutos e tente de novo.':
        'Too many attempts. Wait a few minutes and try again.',
    'para confirmar':
        'to confirm',
    'A sua senha atual não confere. Nada foi apagado.':
        'Your current password does not match. Nothing was deleted.',
    'A sua senha atual não confere. Nada foi alterado.':
        'Your current password does not match. Nothing was changed.',
    'Não foi possível conferir a sua senha agora. Nada foi apagado. Tente de novo em instantes.':
        'Could not check your password right now. Nothing was deleted. Try again in a moment.',
    'Não foi possível conferir a sua senha agora. Nada foi alterado. Tente de novo em instantes.':
        'Could not check your password right now. Nothing was changed. Try again in a moment.',
    'FTP':
        'FTP',
    'Administradores entram com a conta do painel. Usuários do FTP entram com o nome e a senha do FTP '
    'e veem só os arquivos da própria pasta.':
        'Administrators sign in with the panel account. FTP users sign in with the FTP user name and '
        'password and see only the files in their own folder.',
    'Painel de administração da stack.':
        'Administration panel of the stack.',
    'Entrar':
        'Sign in',
    'A página expirou. Tente de novo.':
        'The page expired. Try again.',
    'Não foi possível entrar.':
        'Could not sign in.',
    'O backup dos equipamentos da rede, guardado em um lugar só.':
        'The backup of the network devices, kept in one place.',
    'Cada equipamento preso na própria pasta':
        'Each device confined to its own folder',
    'Painel só por HTTPS, atrás do nginx':
        'Panel over HTTPS only, behind nginx',
    'Sessão encerrada depois de {minutos} minutos sem uso':
        'Session closed after {minutos} minutes without use',
    'Entrar no painel':
        'Sign in to the panel',
    'Uso restrito a quem foi autorizado. As tentativas de entrada ficam registradas.':
        'Restricted to authorized people. Sign-in attempts are recorded.',
    'A pasta passa por um link simbólico, que não é aceito.':
        'The folder goes through a symbolic link, which is not accepted.',
    'Já existe um arquivo com este nome no caminho da pasta.':
        'There is already a file with this name in the folder path.',
    'Não foi possível conferir a pasta.':
        'Could not check the folder.',
    'O comando de usuários não respondeu.':
        'The user command did not respond.',
    'erro sem mensagem':
        'error without a message',
    'sessões no FTP':
        'FTP sessions',
    'download em KB/s':
        'download in KB/s',
    'envio em KB/s':
        'upload in KB/s',
    'horário':
        'hours',
    'downloads pelo painel':
        'downloads through the panel',
    'senhas erradas até o bloqueio':
        'wrong passwords before the block',
    'minutos de bloqueio':
        'minutes of block',
    '{inicio} às {fim}':
        '{inicio} to {fim}',
    'Limite inválido em "{limite}": deixe vazio ou use um número inteiro de {minimo} a {maximo}.':
        'Invalid limit in "{limite}": leave it empty or use a whole number from {minimo} to {maximo}.',
    'Horário inválido: preencha o início e o fim, no formato HH:MM, ou deixe os dois vazios.':
        'Invalid hours: fill in the start and the end, in HH:MM format, or leave both empty.',
    'Horário inválido: o início e o fim não podem ser iguais.':
        'Invalid hours: the start and the end cannot be the same.',
    'nunca bloqueia':
        'never blocks',
    'Operação':
        'Operation',
    'Sistema':
        'System',
    'atenção':
        'attention',
    'problema':
        'problem',
    'não se aplica':
        'not applicable',
    'conferir no servidor':
        'check on the server',
    'Use só para equipamento antigo sem suporte a TLS, em rede interna isolada, e volte para '
    '<code>FTP_TLS_MODE=2</code> assim que puder.':
        'Use it only for old devices without TLS support, on an isolated internal network, and go back '
        'to <code>FTP_TLS_MODE=2</code> as soon as you can.',
    'válido até {data} ({dias} dias)':
        'valid until {data} ({dias} days)',
    'vencido em {data}':
        'expired on {data}',
    'Idioma das telas':
        'Screen language',
    'Usuário do FTP':
        'FTP user',
    'Abas do painel':
        'Panel tabs',
    'Sair':
        'Sign out',
    'só para rede privada, atrás de firewall':
        'private network only, behind a firewall',
    'Pular para o conteúdo':
        'Skip to content',
    'Desenvolvido pela':
        'Developed by',
    '<strong>{quantos} usuário(s) entram no FTP sem TLS</strong> ({nomes}): a senha e os arquivos '
    'deles trafegam em texto puro e podem ser lidos por quem estiver na mesma rede. Use só para '
    'equipamento antigo sem suporte a TLS, em rede interna isolada, e volte a exigir o TLS em <a '
    'href="/usuarios">Usuários</a> assim que puder.':
        '<strong>{quantos} user(s) sign in to FTP without TLS</strong> ({nomes}): their password and '
        'files travel in plain text and can be read by anyone on the same network. Use it only for old '
        'devices without TLS support, on an isolated internal network, and require TLS again under <a '
        'href="/usuarios">Users</a> as soon as you can.',
    'Endereço público aceito (<code>REDE_PERMITIR_IP_PUBLICO=sim</code>), por opção de quem instalou. '
    'FTP e painel na internet são alvo de varredura e de tentativa de senha o tempo todo: mantenha o '
    'firewall do servidor liberando só os endereços dos equipamentos e de quem administra.':
        'Public address accepted (<code>REDE_PERMITIR_IP_PUBLICO=sim</code>), by choice of whoever '
        'installed. FTP and panel on the internet are scanned and hit with password attempts all the '
        'time: keep the server firewall allowing only the addresses of the devices and of whoever '
        'manages it.',
    'Painel publicado por proxy ou túnel (<code>PAINEL_PROXY_CONFIAVEL</code>), por opção de quem '
    'instalou. Quem chega à tela de entrada é decidido lá: restrinja o acesso no proxy ou no túnel. O '
    'FTP não passa por ele.':
        'Panel published through a proxy or tunnel (<code>PAINEL_PROXY_CONFIAVEL</code>), by choice of '
        'whoever installed. Who reaches the sign-in screen is decided there: restrict access at the '
        'proxy or the tunnel. FTP does not go through it.',
    'O FTP está <strong>sem TLS</strong> (<code>FTP_TLS_MODE=0</code>): senhas e arquivos trafegam em '
    'texto puro e podem ser lidos por quem estiver na mesma rede.':
        'FTP is <strong>without TLS</strong> (<code>FTP_TLS_MODE=0</code>): passwords and files travel '
        'in plain text and can be read by anyone on the same network.',
    'O TLS do FTP está <strong>opcional</strong> (<code>FTP_TLS_MODE=1</code>): quem entra sem TLS '
    'manda senha e arquivos em texto puro.':
        'FTP TLS is <strong>optional</strong> (<code>FTP_TLS_MODE=1</code>): whoever signs in without '
        'TLS sends password and files in plain text.',
    'Esta instalação está publicada fora da rede privada: veja como nesta aba':
        'This installation is published outside the private network: see how on this tab',
    '(instalação publicada)':
        '(published installation)',
    'endereço público aceito: confira o firewall':
        'public address accepted: check the firewall',
    'painel publicado por proxy ou túnel':
        'panel published through a proxy or tunnel',
}

# Mensagem de erro do allsafe-ftp-user (ftp/usuario.sh), que fala português sem acento: a expressão que a
# reconhece inteira e o modelo em inglês, com os trechos variáveis nos lugares de \1, \2 e \3.
COMANDO = tuple((re.compile(regra), ingles) for regra, ingles in (
    (r'Perfil invalido: use completo, envio, soenvio ou leitura',
     r'Invalid profile: use completo, envio, soenvio or leitura'),
    (r'Pasta invalida: ate 4 niveis separados por /; letras, numeros, _ - e ponto; nenhum nivel comeca com ponto',
     r'Invalid folder: up to 4 levels separated by /; letters, digits, _ - and dot; no level starts with a dot'),
    (r'Outra alteracao de usuario em andamento; tente de novo', r'Another user change is in progress; try again'),
    (r'Pasta recusada: (.+) e link simbolico', r'Folder refused: \1 is a symbolic link'),
    (r'Pasta recusada: (.+) existe e nao e pasta', r'Folder refused: \1 exists and is not a folder'),
    (r'Limite invalido: (\S+) aceita vazio ou um inteiro de (\d+) a (\d+)',
     r'Invalid limit: \1 accepts empty or a whole number from \2 to \3'),
    (r'Limite invalido: horario aceita vazio ou HHMM-HHMM, com inicio diferente do fim',
     r'Invalid limit: horario accepts empty or HHMM-HHMM, with the start different from the end'),
    (r'Endereco invalido: use um IPv4, como 203\.0\.113\.7',
     r'Invalid address: use an IPv4 address, such as 203.0.113.7'),
    (r'Area de entrada recusada: (.+) passa por link simbolico',
     r'Inbox area refused: \1 goes through a symbolic link'),
    (r'Area de entrada recusada: (.+) existe e nao e pasta', r'Inbox area refused: \1 exists and is not a folder'),
    (r'FTP_MAX_CLIENTS deve ser um inteiro maior que zero',
     r'FTP_MAX_CLIENTS must be a whole number greater than zero'),
    (r'Senha deve ter pelo menos 12 caracteres', r'The password must have at least 12 characters'),
    (r'Usuario ja existe: (.+)', r'User already exists: \1'),
    (r'Usuario nao existe: (.+)', r'User does not exist: \1'),
    (r'Origem invalida: use o endereco IP que aparece em bloqueios',
     r'Invalid origin: use the IP address shown in bloqueios'),
    (r'Endereco nao bloqueavel: (.+) e do proprio servidor',
     r'Address cannot be blocked: \1 belongs to the server itself'),
    (r'Prazo invalido: de 1 a 3650 dias', r'Invalid period: 1 to 3650 days'),
    (r'Pasta dos bloqueios por endereco ausente: reinicie o servico ftp',
     r'Address block folder missing: restart the ftp service'),
    (r'Teto de (\d+) enderecos bloqueados: libere algum antes', r'Ceiling of \1 blocked addresses: release one first'),
))
